### ISSUE TITLE
mvcc  有没有这个问题

### ISSUE THREAD

**Issue by ooooo-youwillsee** [rosedblabs/rust-practice#3]
比如开启事务 t1, t2，（t1 先开启，t2 后开启）

t2  set a b 

t1 set a b  等待锁

t2 commit 

t1 set a b 这时应该成功执行 (看代码逻辑，好像不能成功，原因是 write 方法中，没有判断 version 是否已经提交过)

**Comment by roseduan** [comment]
t1 set a b 的时候会直接报错了
